name: run ws.py

on:
  schedule:
    - cron:'*/5 * * * *'

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:

      - name: check conteudo do repositorio
        uses: actions/checkout@v3

      - name: instalar python
        uses: actions/setup-python@v4
      
      - name: instalar os pacotes do requirements.txt
        uses: python -m pip install pip install -r requerements.txt

      - name: executar o arquivo de scrapping
        run: python scapy.py

